version: '2'
services:
 bot:
  build:
   context: .
   dockerfile: ./docker/slack_connector/Dockerfile
  volumes:
   - ./:/home/dockeruser/project
   - /usr/local/bundle
  command:
    /bin/bash -c "bundle install && bundle exec ruby main.rb"
  env_file: .slack.env
